export const articles = [
    {
        title: "Massiivinen Tripla kiilaa koollaan Suomen ostoskeitaiden kärkikolmikkoon ja on pian lähin kauppakeskus yli 100 000:lle joukkoliikenteen käyttäjälle",
        url: "https://yle.fi/uutiset/3-11016106",
        image_id: "39-5893575d762b795ff2f",
        published: "14.10.2019",
        publisher: "Yle",
        role: "code",
    },
    {
        title: "Vanhusten palvelutaloihin tehdään vain harvoin yllätystarkastuksia – katso, kuinka sinun kuntasi valvoo ikäihmisten oloja",
        url: "https://yle.fi/uutiset/3-10734160",
        image_id: "13-3-10731896",
        published: "24.4.2019",
        publisher: "Yle",
        role: "code",
    },
    {
        title: "Äärioikeistolainen lapuanliike muilutti, murhasi ja terrorisoi – Jaakko Kosola on kuuluisaa sukua ja kantaa historian arpia mukanaan",
        url: "https://yle.fi/uutiset/3-11068956",
        image_id: "39-6237985df8ea2ff41a3",
        published: "21.12.2019",
        publisher: "Yle",
        role: "code",
    },
    {
        title: "\"Mitä nää uudet sanat on? Yhtäkkii mä käytän niit\" – tämän jutun äikän ope haluaisi sinulta kieltää, mutta lukee itse salaa",
        url: "https://yle.fi/uutiset/3-11089578",
        image_id: "13-3-11103569",
        published: "8.12.2019",
        publisher: "Yle",
        role: "code",
    },
    {
        title: "\"Perhe on vähän vanhanaikainen haave\" – Ylen kone näyttää, kuinka moni ikäisesi asuu yksin",
        url: "https://yle.fi/uutiset/3-11088126",
        image_id: "39-6160635ddd28eb92bf2",
        published: "28.11.2019",
        publisher: "Yle",
        role: "code",
    },
    {
        title: "Suomessa ajetaan vuosittain tuhansia hirvikolareita – katso kartasta, millä teillä pelti rytisee",
        url: "https://yle.fi/uutiset/3-10946241",
        image_id: "13-3-10947472",
        published: "4.9.2019",
        publisher: "Yle",
        role: "code, writing",
    },
    {
        title: "Kaksoismurhaajan jahtaaminen oli viedä poliisin epätoivoon – suohon kätketty salaisuus raottuu Tulilahden tutkintamateriaalista",
        url: "https://yle.fi/uutiset/3-10881289",
        image_id: "13-3-10883209",
        published: "19.7.2019",
        publisher: "Yle",
        role: "code",
    },
    {
        title: "Onko Helsingissä pian yhtä kuuma kuin Montenegrossa? Katso, miten suomalaiset kaupungit lämpenevät vuoteen 2080 mennessä",
        url: "https://yle.fi/uutiset/3-10346334",
        image_id: "13-3-10374675",
        published: "1.9.2018",
        publisher: "Yle",
        role: "writing",
    },
    {
        title: "Donald Trumpin presidenttikausi ei ole vakuuttanut suomalaisia – vain ani harva uskoo Trumpin tehneen maailmasta turvallisemman",
        url: "https://yle.fi/uutiset/3-10277828",
        image_id: "13-3-10287820",
        published: "9.7.2018",
        publisher: "Yle",
        role: "writing",
    },
    {
        title: "Hyvätapainen televisiotähti vai kovasanainen kiinteistöhai? – tällainen vieras Donald Trump saattaisi olla, jos hän astuisi sinun kotiisi",
        url: "https://yle.fi/uutiset/3-10289879",
        image_id: "13-3-10302881",
        published: "15.7.2018",
        publisher: "Yle",
        role: "writing",
    },
    {
        title: "Suomalaisten lempikarkin hämmentävä ristiriita – salmiakki on terveellinen, mutta samaan aikaan terveydelle vaarallinen herkku",
        url: "https://yle.fi/uutiset/3-10805175",
        image_id: "13-3-10805719",
        published: "2.6.2019",
        publisher: "Yle",
        role: "code",
    },
    {
        title: "Katso, mistä löytyvät vaarallisimmat tiet ja kuumapäisimmät kuskit – \"Kaikilla on raja, jonka jälkeen kiehahtaa yli\"",
        url: "https://yle.fi/uutiset/3-11116844",
        image_id: "39-6297195e1845bd6f04b",
        published: "11.1.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        title: "Näin Trumpin ja Kimin tapaaminen huomioitiin Pohjois-Korean mediassa – pohjoiskorealaiset seurasivat lähetystä Pjongjangin rautatieasemalla",
        url: "https://yle.fi/uutiset/3-10249603",
        image_id: "13-3-10249645",
        published: "12.6.2018",
        publisher: "Yle",
        role: "writing",
    },
    {
        title: "Purkutuomion saanut kerrostalo teki viimeisen palveluksensa – muuttui värikkääksi festaripaikaksi",
        url: "https://yle.fi/uutiset/3-8212940",
        image_id: "13-3-8213008",
        published: "9.8.2015",
        publisher: "Yle",
        role: "writing",
    },
    {
        title: "Thaimaassa luolasta pelastetut pojat kertovat, kuinka he joivat sadevettä tippukivistä ja yrittivät kaivaa tietään ulos – Yle seurasi hetki hetkeltä",
        url: "https://yle.fi/uutiset/3-10310825",
        image_id: "13-3-10311352",
        published: "18.7.2018",
        publisher: "Yle",
        role: "writing",
    },
    {
        title: "Unkari muuttaa perustuslakiaan – uusi laki tekee turvapaikanhakijoiden auttamisesta rangaistavaa",
        url: "https://yle.fi/uutiset/3-10266522",
        image_id: "13-3-10266670",
        published: "20.6.2018",
        publisher: "Yle",
        role: "writing",
    },
    {
        title: "Mustikka kukkii parhaiten 22 vuoteen – sadosta kypsymässä hyvin runsas",
        url: "https://yle.fi/uutiset/3-8106280",
        image_id: "13-3-6794021",
        published: "26.6.2015",
        publisher: "Yle",
        role: "writing",
    },
    {
        title: "Perussuomalaisten Sebastian Tynkkynen: BB-tähdestä puolueen varapuheenjohtajaksi",
        url: "https://yle.fi/uutiset/3-8213407",
        image_id: "13-3-8213448",
        published: "9.8.2015",
        publisher: "Yle",
        role: "writing",
    },
    {
        title: "Tämä on kertomus saamenpuvuista – aviomies halusi säpikkäisiinsä vihreää, sillä vaimo on kotoisin Lemmenjoen mäntymetsästä – Gákti čatná olbmuid oktii: vihtta gáktemuitalusa",
        url: "https://yle.fi/uutiset/3-11191637",
        image_id: "39-6391335e3abe44dee40",
        published: "5.2.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        title: "Avantouinti on nyt niin suosittua, että jäihin pitää jonottaa – katso, miten liha kangistuu ja nahka höyryää Suomen vilkkaimmalla avannolla",
        url: "https://yle.fi/uutiset/3-11192805",
        image_id: "39-6381075e38278eba158",
        published: "8.2.2020",
        publisher: "Yle",
        role: "code",
    },
]