/* ------ Import print images ------ */
import avautuvat_sotilassaaret from "./../../img/print/avautuvat-sotilassaaret.jpg";
import kutsuntaliite from "./../../img/print/kutsuntaliite-2014.jpg";
import kaupunkisotilas_ja_siviili from "./../../img/print/kaupunkisotilas-ja-siviili.jpg";
import yhteiskuntaa_karkuun from "./../../img/print/yhteiskuntaa-karkuun-kiven-sisaan.jpg";

export const articles = [
    {
        type: "web",
        title: "Massiivinen Tripla kiilaa koollaan Suomen ostoskeitaiden kärkikolmikkoon ja on pian lähin kauppakeskus yli 100 000:lle joukkoliikenteen käyttäjälle",
        url: "https://yle.fi/uutiset/3-11016106",
        image_id: "39-5893575d762b795ff2f",
        published: "14.10.2019",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Vanhusten palvelutaloihin tehdään vain harvoin yllätystarkastuksia – katso, kuinka sinun kuntasi valvoo ikäihmisten oloja",
        url: "https://yle.fi/uutiset/3-10734160",
        image_id: "13-3-10731896",
        published: "24.4.2019",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Äärioikeistolainen lapuanliike muilutti, murhasi ja terrorisoi – Jaakko Kosola on kuuluisaa sukua ja kantaa historian arpia mukanaan",
        url: "https://yle.fi/uutiset/3-11068956",
        image_id: "39-6237985df8ea2ff41a3",
        published: "21.12.2019",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "\"Mitä nää uudet sanat on? Yhtäkkii mä käytän niit\" – tämän jutun äikän ope haluaisi sinulta kieltää, mutta lukee itse salaa",
        url: "https://yle.fi/uutiset/3-11089578",
        image_id: "13-3-11103569",
        published: "8.12.2019",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "\"Perhe on vähän vanhanaikainen haave\" – Ylen kone näyttää, kuinka moni ikäisesi asuu yksin",
        url: "https://yle.fi/uutiset/3-11088126",
        image_id: "39-6160635ddd28eb92bf2",
        published: "28.11.2019",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Suomessa ajetaan vuosittain tuhansia hirvikolareita – katso kartasta, millä teillä pelti rytisee",
        url: "https://yle.fi/uutiset/3-10946241",
        image_id: "13-3-10947472",
        published: "4.9.2019",
        publisher: "Yle",
        role: "code, writing",
    },
    {
        type: "web",
        title: "Kaksoismurhaajan jahtaaminen oli viedä poliisin epätoivoon – suohon kätketty salaisuus raottuu Tulilahden tutkintamateriaalista",
        url: "https://yle.fi/uutiset/3-10881289",
        image_id: "13-3-10883209",
        published: "19.7.2019",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Onko Helsingissä pian yhtä kuuma kuin Montenegrossa? Katso, miten suomalaiset kaupungit lämpenevät vuoteen 2080 mennessä",
        url: "https://yle.fi/uutiset/3-10346334",
        image_id: "13-3-10374675",
        published: "1.9.2018",
        publisher: "Yle",
        role: "writing",
    },
    {
        type: "web",
        title: "Donald Trumpin presidenttikausi ei ole vakuuttanut suomalaisia – vain ani harva uskoo Trumpin tehneen maailmasta turvallisemman",
        url: "https://yle.fi/uutiset/3-10277828",
        image_id: "13-3-10287820",
        published: "9.7.2018",
        publisher: "Yle",
        role: "writing",
    },
    {
        type: "web",
        title: "Hyvätapainen televisiotähti vai kovasanainen kiinteistöhai? – tällainen vieras Donald Trump saattaisi olla, jos hän astuisi sinun kotiisi",
        url: "https://yle.fi/uutiset/3-10289879",
        image_id: "13-3-10302881",
        published: "15.7.2018",
        publisher: "Yle",
        role: "writing",
    },
    {
        type: "web",
        title: "Suomalaisten lempikarkin hämmentävä ristiriita – salmiakki on terveellinen, mutta samaan aikaan terveydelle vaarallinen herkku",
        url: "https://yle.fi/uutiset/3-10805175",
        image_id: "13-3-10805719",
        published: "2.6.2019",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Katso, mistä löytyvät vaarallisimmat tiet ja kuumapäisimmät kuskit – \"Kaikilla on raja, jonka jälkeen kiehahtaa yli\"",
        url: "https://yle.fi/uutiset/3-11116844",
        image_id: "39-6297195e1845bd6f04b",
        published: "11.1.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Näin Trumpin ja Kimin tapaaminen huomioitiin Pohjois-Korean mediassa – pohjoiskorealaiset seurasivat lähetystä Pjongjangin rautatieasemalla",
        url: "https://yle.fi/uutiset/3-10249603",
        image_id: "13-3-10249645",
        published: "12.6.2018",
        publisher: "Yle",
        role: "writing",
    },
    {
        type: "web",
        title: "Purkutuomion saanut kerrostalo teki viimeisen palveluksensa – muuttui värikkääksi festaripaikaksi",
        url: "https://yle.fi/uutiset/3-8212940",
        image_id: "13-3-8213008",
        published: "9.8.2015",
        publisher: "Yle",
        role: "writing",
    },
    {
        type: "web",
        title: "Thaimaassa luolasta pelastetut pojat kertovat, kuinka he joivat sadevettä tippukivistä ja yrittivät kaivaa tietään ulos – Yle seurasi hetki hetkeltä",
        url: "https://yle.fi/uutiset/3-10310825",
        image_id: "13-3-10311352",
        published: "18.7.2018",
        publisher: "Yle",
        role: "writing",
    },
    {
        type: "web",
        title: "Unkari muuttaa perustuslakiaan – uusi laki tekee turvapaikanhakijoiden auttamisesta rangaistavaa",
        url: "https://yle.fi/uutiset/3-10266522",
        image_id: "13-3-10266670",
        published: "20.6.2018",
        publisher: "Yle",
        role: "writing",
    },
    {
        type: "web",
        title: "Mustikka kukkii parhaiten 22 vuoteen – sadosta kypsymässä hyvin runsas",
        url: "https://yle.fi/uutiset/3-8106280",
        image_id: "13-3-6794021",
        published: "26.6.2015",
        publisher: "Yle",
        role: "writing",
    },
    {
        type: "web",
        title: "Perussuomalaisten Sebastian Tynkkynen: BB-tähdestä puolueen varapuheenjohtajaksi",
        url: "https://yle.fi/uutiset/3-8213407",
        image_id: "13-3-8213448",
        published: "9.8.2015",
        publisher: "Yle",
        role: "writing",
    },
    {
        type: "web",
        title: "Tämä on kertomus saamenpuvuista – aviomies halusi säpikkäisiinsä vihreää, sillä vaimo on kotoisin Lemmenjoen mäntymetsästä – Gákti čatná olbmuid oktii: vihtta gáktemuitalusa",
        url: "https://yle.fi/uutiset/3-11191637",
        image_id: "39-6391335e3abe44dee40",
        published: "5.2.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Avantouinti on nyt niin suosittua, että jäihin pitää jonottaa – katso, miten liha kangistuu ja nahka höyryää Suomen vilkkaimmalla avannolla",
        url: "https://yle.fi/uutiset/3-11192805",
        image_id: "39-6381075e38278eba158",
        published: "8.2.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Kuoppaisella tiellä ambulanssikyytikin kestää kauemmin – Suomessa on tuhansia kilometrejä huonoja teitä, katso kartasta oman kuntasi tilanne",
        url: "https://yle.fi/uutiset/3-11228875",
        image_id: "39-6474095e57711235dd1",
        published: "4.3.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "print",
        title: "Avautuvat sotilassaaret – Puolustusvoimien vuokralaisuus sotilassaarilla päättyy. Miltä saarten tulevaisuus näyttää?",
        url: "https://drive.google.com/file/d/1qbTA0E3qbq5oDLrAxuo-_cNpJsqZMqxa/view?usp=sharing",
        image_id: avautuvat_sotilassaaret,
        published: "26.6.2014",
        publisher: "Ruotuväki",
        role: "writing",
    },
    {
        type: "print",
        title: "Kutsuntaliite 2014 – Kutsuntojen kautta asevelvollisuuden matkalle",
        url: "https://drive.google.com/file/d/15uCUsIVqhioFFdOI7-bm6ahZqHcm97TL/view?usp=sharing",
        image_id: kutsuntaliite,
        published: "17.7.2014",
        publisher: "Ruotuväki",
        role: "writing",
    },
    {
        type: "print",
        title: "Kaupunkisotilas & siviili",
        url: "https://drive.google.com/file/d/1PQSTiNn24AFKnxosjzPy37TScCqIwDjt/view?usp=sharing",
        image_id: kaupunkisotilas_ja_siviili,
        published: "3.4.2014",
        publisher: "Ruotuväki",
        role: "writing",
    },
    {
        type: "print",
        title: "Yhteiskuntaa karkuun kiven sisään",
        url: "https://drive.google.com/file/d/1yg0uMZFYjl6qvSv-ZxFdN_qMgwMOKglo/view?usp=sharing",
        image_id: yhteiskuntaa_karkuun,
        published: "15.1.2015",
        publisher: "Utain",
        role: "writing",
    },
    {
        type: "web",
        title: "Jos koronatilanne ahdistaa, on hyvä hetki pysähtyä miettimään omaa elämää – testaa tästä, kuinka onnellinen olet",
        url: "https://yle.fi/uutiset/3-11263263",
        image_id: "39-6556815e7470b15a6e1",
        published: "21.3.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Ylen selvitys: Liikennemäärä Uudenmaan rajoilla on jo merkittävästi vähentynyt",
        url: "https://yle.fi/uutiset/3-11277639",
        image_id: "39-6566855e78b2ecf3b81",
        published: "26.3.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Mikä on surumuna, mitä kertoo munan koodi ja onko vapaa kana vapaa? Suomalainen syö 12 kiloa munia vuodessa ja siksi on hyvä tietää, mitä syö",
        url: "https://yle.fi/uutiset/3-11290114",
        image_id: "13-3-11290540",
        published: "4.4.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Tulipalo saa yleensä alkunsa liedeltä, mutta vanha vitsaus aiheuttaa edelleen eniten kuolemia – katso kartasta, missä ja miten rakennukset palavat Tampereella",
        url: "https://yle.fi/uutiset/3-11325984",
        image_id: "13-3-11341810",
        published: "8.5.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Ylen selvitys: toimeentulotuen uudistus on epäonnistunut kaikkein heikompiosaisten kohdalla – lue Jaron, Sirpan, Ilmin ja Johannan tarinat köyhyydestä",
        url: "https://yle.fi/uutiset/3-11351353",
        image_id: "13-3-11350850",
        published: "19.5.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Kysyimme, mitä on hyvä elämä ja näin suomalaiset vastasivat – testaa, ovatko sinulle tärkeät asiat tärkeitä myös muille",
        url: "https://yle.fi/uutiset/3-11360661",
        image_id: "39-5696215cfe5f8d5cfc3",
        published: "22.5.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Henkirikokset rajussa kasvussa tänä keväänä, poliisi: \"Ei ole kontrollia, minne veitsen isku päätyy\" – katso kartalta 2000-luvun Suomen väkivaltaisimmat paikat",
        url: "https://yle.fi/uutiset/3-11383347",
        image_id: "13-3-11405609",
        published: "17.6.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "35 000 miestä rakensi Suomen halki valtavan rakennelman, joka kestää vaikka tykkitulen – katso, miten Salpalinja syntyi ja mitä siitä on jäljellä",
        url: "https://yle.fi/uutiset/3-11403518",
        image_id: "13-3-11408424",
        published: "21.6.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Nyt on paras hetki rakentaa muodikas ötökkähotelli, mutta asuuko niissä oikeasti hyönteisiä? – Katso, millaisia asukkaita hotellissamme majailee",
        url: "https://yle.fi/uutiset/3-11417908",
        image_id: "13-3-11454139",
        published: "23.7.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Katso, kuinka vihreä kotikuntasi on – vertasimme Suomen kaikkia kuntia viidellä eri kriteerillä, ja mallioppilaat erottuvat joukosta",
        url: "https://yle.fi/uutiset/3-11504485",
        image_id: "13-3-11513638",
        published: "3.9.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Saaʹmi ouddoummuvaali võboršeǩ-kueiʹtes ǩeâsttâʹlle vuäʹmm tååimast – Kolttien luottamusmiesvaalin ehdokaskaksikko kisaa ikivanhasta luottamustoimesta",
        url: "https://yle.fi/uutiset/3-11516665",
        image_id: "39-7124345f477ebe917ac",
        published: "3.9.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Moni meistä ajattelee kuin Jari Matikainen: Biojätteen lajittelu on liian hankalaa – siksi valtava määrä ruokaa poltetaan sekajätteen mukana",
        url: "https://yle.fi/uutiset/3-11533305",
        image_id: "39-7188865f605bb2a1dd1",
        published: "21.9.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Katso kartasta, mitkä rikollisorganisaatiot kokoontuvat kotikulmillasi – KRP: jengitilanne voimakkaassa muutoksessa United Brotherhoodin väliaikaisen toimintakiellon vuoksi",
        url: "https://yle.fi/uutiset/3-11542665",
        image_id: "14-svyle-499531971e593882",
        published: "26.9.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "\"Nainen ei saa olla seksikäs, mies ei saa itkeä\" – 1 200 opiskelijaa vastasi, miten sukupuolinormit vaikuttavat heidän elämäänsä",
        url: "https://yle.fi/uutiset/3-11570381",
        image_id: "13-3-11580957",
        published: "13.10.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "George Floydin kuolinkaupunki on hengenvaarallinen monelle mustalle – Minneapolisin kadut tunteva Queen haluaa estää uudet kuolemat, ja yksi ratkaisu löytyy asumisesta",
        url: "https://yle.fi/uutiset/3-11603775",
        image_id: "39-7355115f997c1cb3aea",
        published: "1.11.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Mitä teet, kun pieni koululainen kertoo nähneensä pornoa kaverin puhelimesta? Testaa pelissä, miten selviydytte vaikeasta paikasta yhdessä",
        url: "https://yle.fi/uutiset/3-11603623",
        image_id: "13-3-11623822",
        published: "9.11.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Onnea uusille ylioppilaille! Ylen Ylioppilaskoneesta näet, kuka saa valkolakin",
        url: "https://yle.fi/uutiset/3-11615342",
        image_id: "13-3-11633000",
        published: "12.11.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Ylen toimittaja soluttautui hämärille eläinmarkkinoille – koirasusien kasvatus ja myynti kiellettiin lailla, mutta kauppa käy yhä",
        url: "https://yle.fi/uutiset/3-11689345",
        image_id: "39-7524315fd0ca55e7dcc",
        published: "10.12.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Kun Mannerheim halusi viettää löhölomaa, hän lähti metsästysmajalleen, jossa ei koskaan metsästetty – tutustu Marskin majaan",
        url: "https://yle.fi/uutiset/3-11688673",
        image_id: "13-3-11689391",
        published: "11.12.2020",
        publisher: "Yle",
        role: "code",
    },
    {
        type: "web",
        title: "Suomalaisten ruokavalio kuuluu EU:n pahiksiin – kokeile Ylen ruokakoneella, miten lounaalla tekemäsi valinnat vaikuttavat ympäristöön",
        url: "https://yle.fi/uutiset/3-11699920",
        image_id: "13-3-11714060",
        published: "1.1.2021",
        publisher: "Yle",
        role: "code",
    },
]